---
title: "Conclusion"
---

People often face multiple competing influences when making a decision – especially those containing elements of ethicality. Understanding the interplay between the many competing heuristics, contextual influences, and biases can provide useful insights into the cognitive processes that underlie these difficult choices.  Two such factors – self-control depletion and framing effects – have both been shown to play meaningful roles in this important area of study.  Prior research conducted by Grolleau et al., (2016) suggests that people are more likely to cheat when faced with a loss than when faced with a gain while a study conducted by Mead et al., (2009) found that self-control depletion led to an increase in cheating behaviors.

Surprisingly, research into the effects of biases and heuristics on cheating behavior has generally been conducted independently.  In an effort to address this research gap, we instead set out to examine the combined effect of self-control depletion and framing effects on cheating behavior using a two-by-two experimental design.  Participants were asked to complete an initial depletion task after which they completed a challenging matrix task.  Once the matrices task was completed, participants were instructed to self-administer raffle tickets based on how many matrices they solved correctly.  Both the depletion task (depleted vs. non-depleted) and the process by which the raffle tickets were issued (gain vs. loss frame) were varied according to the treatment conditions.   Based on the prior literature, we hypothesized that depletion and loss framing would both lead to incrementally more cheating behavior.  More importantly, we anticipated that the combined interaction of these two factors would lead to a compounding effect that would further motivate cheating.

Overall, participants in this study cheated less frequently than participants in previous studies using a similar task (Mead et al., 2009; Grolleau et al., 2016).  The results supported our second hypothesis that participants under the loss condition cheated to a greater magnitude than those under the gain condition. However, these findings do not support our first hypothesis - the results suggest no effect of depletion on either occurrence of cheating nor magnitude of cheating. Findings also do not support th third hypothesis that participants who were presented with a loss after being depleted cheated more than those in the other treatment conditions.

Next, I offer a few explanations as to why I did not see the results I expected to see. The absence of cheating behavior was likely due, in part, to our incentive structure, which relied upon the distribution of raffle tickets.  If, in fact, that is the case, this outcome suggests that further research into the framing effects on non-monetary incentives is warranted.  Our results also point to the challenge of systematically creating a state of self-control depletion and the possibility that depletion tasks are actually creating a state of cognitive load.

Despite the fact that the data did not support our hypotheses, a deeper understanding of the driving forces behind cheating is imperative to inform the design of systems that present the opportunity to engage in deceitful behavior. At a general level, the impact of depletion is crucial as actions may be taken to minimize the exertion on self-control when engaging in decision-making that presents the opportunity to cheat, should further research support the finding that depleted individuals are more likely to engage in such behavior than non-depleted individuals (which cannot be confirmed by our results). Furthermore, the salience of a perceived loss should be minimized and where possible, reframed as a gain, given that loss framing resulted in a greater magnitude of cheating than gain framing. Below is an example of how to apply these general findings in a natural extension of cheating behavior: tax evasion. Tax evasion remains one of the costliest deceitful behaviors to society, resulting in an estimated $450 billion of lost revenues annually (Internal Revenue Service, 2016). While some of this lost revenue is driven by large-scale, sophisticated attempts to avoid paying significant sums of money, there is undoubtedly a portion arising from behavior that is more similar to that observed in our experiment – evading relatively small sums because the taxpayer feels entitled to keep a larger percentage of the income they have earned (because it is too difficult to report on accurate numbers, or because the filing system is designed in such a way that makes paying taxes feel like a loss). If further research confirms that depletion increases the likelihood and magnitude of cheating behavior, then governments may consider subsidizing private tax software programs to provide as a free service given many of the issues noted above have been addressed in the design of such programs. Features such as immediate rollover from year to year of consistent information, automatic execution of calculations, search for relevant deductions and credits, and pre-population of necessary additional forms minimize the amount of mental energy involved thus reducing depletion and increasing likelihood that income will be reported accurately. Further research is required to fully understand the implications of each technical feature, however, we believe that our results provide a meaningful starting point to explore an investment in tax preparation software, which we hypothesize would ultimately result in a sufficient increase in compliance to offset the associated cost.


