---
title: "Introduction"
---

In recent years, there has been an explosion of research regarding people’s decision making behaviors and the contextual factors that contribute to such decisions. This has led to the identification of systematic cognitive biases in decision making such as “the framing effect,” by which an individual’s decision making is influenced by whether a decision or its outcomes are presented as gains or losses relative to a reference point (Tversky & Kahneman, 1981). Additionally, individual factors such as self-control depletion have been suggested to play a role in decision making behaviors (Baumeister et al., 2007). Biases and individual factors have been shown to influence behaviors in many areas of decision making. 

One area of interest for scholars has been that of behavioral ethics. Many researchers have sought to understand what leads individuals to engage in immoral behaviors such as cheating and lying. Studies have been able to identify contextual factors and circumstances that lead individuals to higher rates of cheating and lying. In line with other areas of decision making, systematic biases and contextual factors have been shown to lead to more or less cheating in different situations. Research conducted by Grolleau et al., (2016) suggests that people are more likely to cheat when faced with a loss than when faced with a gain. Additionally, results from a study conducted by Mead et al., (2009) found that self-control depletion led to an increase in cheating behaviors.

Interestingly, little research has been conducted to evaluate the compound effect of biases with individual factors on decision making. For example, little is known about how individuals make choices when they are depleted of self-control and faced with differently framed choices. Rather, the literature typically focuses on one factor at a time in isolation. This makes sense from an experimental practicality standpoint, but does not capture the full picture of how decisions are made in the real world. People often face multiple competing influences when making a decision. Understanding how competing heuristics, contextual influences, and biases are resolved provides some insight on decision maker’s cognitive processes.  It is possible that these influences may be compounding, leading to more reliance on heuristics or biases to make decisions or multiple influences to be enacted at once. For example, does self-control depletion exacerbate the reliance on framing effects? Alternatively, the presence of multiple factors may lead to one factor being more dominant than the others. Does being tired override loss aversion and make decision makers more conservative when faced with a loss? Studies are needed to understand how situations like this will be resolved in the mind of the decision maker and what implications this has for decisions ranging from ethics to consumer behavior to policy. For example, deceptive behavior involving taxes, materialized through underreporting of income, results in an estimated $450 billion in lost revenues annually (Internal Revenue Service, 2016). Understanding the mechanisms behind this deviant behavior, and subsequently informing design modification and allocation of monitoring resources to scenarios in which this deceptive behavior is most likely to occur has tremendous potential to recover a significant portion of lost revenues. 

The purpose of the current study was to evaluate cheating behaviors in a context where participants are both depleted of their self-control and compensation is framed as a gain or loss. Participants took an online study conducted in the field in different locations across the University of Pennsylvania Campus. They were randomly assigned to one of four conditions: depleted_loss, depleted_gain, non-depleted_loss, and non-depleted_gain. The study allowed us to test three hypotheses: (1) Regardless of loss/gain framing, participants depleted of self-control will cheat more, on average, than non-depleted participants; (2) Loss framing will lead to more cheating relative to gain framing, regardless of self-control depletion or lack thereof; and (3) The average rate/amount of cheating demonstrated will be greatest for participants who are depleted of self-control and operating under a loss frame. 
